# Generated by Django 3.2.9 on 2021-12-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers_and_dealer_centers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_mileage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Пробег'),
        ),
    ]
