# Generated by Django 3.2.9 on 2021-12-01 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealers_and_dealer_centers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealer',
            old_name='admin',
            new_name='user',
        ),
    ]
