# Generated by Django 3.2.9 on 2021-12-04 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealers_and_dealer_centers', '0002_alter_vehicle_vehicle_mileage'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclePhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='vehicle_photos/%Y/%m/%d/', verbose_name='Фотография')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dealers_and_dealer_centers.vehicle', verbose_name='Транспортное средство')),
            ],
            options={
                'verbose_name': 'Фотография транспортного средства',
                'verbose_name_plural': 'Фотографии транспортного средства',
            },
        ),
    ]
