# Generated by Django 3.2.9 on 2021-12-01 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealers_and_dealer_centers', '0002_rename_admin_dealer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealercenter',
            old_name='admin',
            new_name='user',
        ),
    ]
