# Generated by Django 3.2.9 on 2021-12-10 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealers_and_dealer_centers', '0003_vehiclephotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclephotos',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_images', to='dealers_and_dealer_centers.vehicle', verbose_name='Транспортное средство'),
        ),
    ]
