# Generated by Django 3.2.9 on 2021-12-15 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dealers_and_dealer_centers', '0005_dealercenterreviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealercenterreviews',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата написания отзыва'),
            preserve_default=False,
        ),
    ]
