# Generated by Django 3.2.9 on 2021-12-16 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealers_and_dealer_centers', '0006_dealercenterreviews_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealercenterreviews',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dealers_and_dealer_centers.dealercenterreviews', verbose_name='Родитель'),
        ),
    ]
